/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pokemonapp.ui;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author SergioJimenezDev
 */
public class frameCombate extends javax.swing.JFrame {
    
    /**
     * Creates new form frameCombate
     */
    public frameCombate() {
        setTitle("PokeApp by SergioJimenezDev.com");
        setIconImage(new ImageIcon(getClass().getResource("/pokemonapp/src/Oak.png")).getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgInicio = new javax.swing.JLabel();
        imgInicio1 = new javax.swing.JLabel();
        btnInicial = new javax.swing.JButton();
        txtAreaInicial = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnHabilidad1 = new javax.swing.JButton();
        btnHabilidad2 = new javax.swing.JButton();
        btnHabilidad3 = new javax.swing.JButton();
        btnHabilidad4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtVidaPokemon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVidaOak = new javax.swing.JLabel();
        bulbasaurPng = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        imgInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonapp/src/pokeball.png"))); // NOI18N
        getContentPane().add(imgInicio);
        imgInicio.setBounds(990, 580, 30, 40);

        imgInicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonapp/src/pokeball.png"))); // NOI18N
        getContentPane().add(imgInicio1);
        imgInicio1.setBounds(80, 580, 30, 40);

        btnInicial.setBackground(new java.awt.Color(0, 116, 217));
        btnInicial.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        btnInicial.setForeground(new java.awt.Color(255, 255, 255));
        btnInicial.setText("COMENZAR");
        btnInicial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 86, 163), new java.awt.Color(0, 87, 163), new java.awt.Color(0, 86, 163), new java.awt.Color(0, 86, 163)));
        btnInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicialMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInicialMousePressed(evt);
            }
        });
        btnInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicialActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicial);
        btnInicial.setBounds(120, 550, 860, 90);

        txtAreaInicial.setBackground(new java.awt.Color(204, 204, 204));
        txtAreaInicial.setColumns(20);
        txtAreaInicial.setFont(new java.awt.Font("Kristen ITC", 0, 30)); // NOI18N
        txtAreaInicial.setForeground(new java.awt.Color(0, 0, 0));
        txtAreaInicial.setLineWrap(true);
        txtAreaInicial.setRows(5);
        txtAreaInicial.setText("PokeApp es una aplicación con interfaz gráfica que pretende simular un combate pokemon. En este caso, no todo fue como lo previsto.\n\nTe encuentras en Pueblo Paleta, dispuesto a comenzar tu aventura, el profesor Oak te llamó para ir a su laboratorio, así que bajas las escaleras, le das dos besos a tu madre y sales con ánimo de conquitas todas las regiones.\n\nAl llegar al laboratorio te das cuenta que todo era una trampa, pretende raptarte. Te encuetras una pokeball por el suelo que resulta ser un Bulbasaur y te dispones a defenderte del profesor");
        txtAreaInicial.setWrapStyleWord(true);
        txtAreaInicial.setPreferredSize(new java.awt.Dimension(1000, 902));
        getContentPane().add(txtAreaInicial);
        txtAreaInicial.setBounds(0, 0, 1090, 710);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonapp/src/pokeball.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(950, 410, 30, 40);

        btnHabilidad1.setBackground(new java.awt.Color(0, 116, 217));
        btnHabilidad1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        btnHabilidad1.setForeground(new java.awt.Color(255, 255, 255));
        btnHabilidad1.setText("LÁTIGO CEPA");
        btnHabilidad1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 86, 163), new java.awt.Color(0, 86, 163), new java.awt.Color(0, 86, 163), new java.awt.Color(0, 86, 163)));
        btnHabilidad1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHabilidad1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHabilidad1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHabilidad1MousePressed(evt);
            }
        });
        btnHabilidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilidad1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnHabilidad1);
        btnHabilidad1.setBounds(690, 500, 180, 90);

        btnHabilidad2.setBackground(new java.awt.Color(0, 116, 217));
        btnHabilidad2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        btnHabilidad2.setForeground(new java.awt.Color(255, 255, 255));
        btnHabilidad2.setText("DEFENSA FERREA");
        btnHabilidad2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 86, 163), new java.awt.Color(0, 87, 163), new java.awt.Color(0, 86, 163), new java.awt.Color(0, 86, 163)));
        btnHabilidad2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHabilidad2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHabilidad2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHabilidad2MousePressed(evt);
            }
        });
        btnHabilidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilidad2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnHabilidad2);
        btnHabilidad2.setBounds(890, 500, 180, 90);

        btnHabilidad3.setBackground(new java.awt.Color(0, 116, 217));
        btnHabilidad3.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        btnHabilidad3.setForeground(new java.awt.Color(255, 255, 255));
        btnHabilidad3.setText("DANZA ESPADA");
        btnHabilidad3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 86, 163), new java.awt.Color(0, 86, 163), new java.awt.Color(0, 86, 163), new java.awt.Color(0, 86, 163)));
        btnHabilidad3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHabilidad3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHabilidad3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHabilidad3MousePressed(evt);
            }
        });
        btnHabilidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilidad3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnHabilidad3);
        btnHabilidad3.setBounds(690, 600, 180, 90);

        btnHabilidad4.setBackground(new java.awt.Color(0, 116, 217));
        btnHabilidad4.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        btnHabilidad4.setForeground(new java.awt.Color(255, 255, 255));
        btnHabilidad4.setText("DRENAJE");
        btnHabilidad4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 86, 163), new java.awt.Color(0, 86, 163), new java.awt.Color(0, 86, 163), new java.awt.Color(0, 86, 163)));
        btnHabilidad4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHabilidad4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHabilidad4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHabilidad4MousePressed(evt);
            }
        });
        getContentPane().add(btnHabilidad4);
        btnHabilidad4.setBounds(890, 600, 180, 90);

        txtArea.setEditable(false);
        txtArea.setBackground(new java.awt.Color(42, 42, 42));
        txtArea.setColumns(20);
        txtArea.setForeground(new java.awt.Color(255, 255, 255));
        txtArea.setRows(5);
        txtArea.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtArea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 500, 650, 190);

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("BULBASAUR:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 460, 190, 40);

        txtVidaPokemon.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        txtVidaPokemon.setForeground(new java.awt.Color(51, 255, 51));
        txtVidaPokemon.setText("100/100");
        getContentPane().add(txtVidaPokemon);
        txtVidaPokemon.setBounds(890, 460, 100, 40);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("OAK:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(37, 21, 80, 30);

        txtVidaOak.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        txtVidaOak.setForeground(new java.awt.Color(51, 255, 51));
        txtVidaOak.setText("100/100");
        getContentPane().add(txtVidaOak);
        txtVidaOak.setBounds(120, 20, 100, 30);

        bulbasaurPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonapp/src/bulbasourGrande.png"))); // NOI18N
        getContentPane().add(bulbasaurPng);
        bulbasaurPng.setBounds(20, 160, 370, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonapp/src/Oak.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(750, 70, 220, 390);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonapp/src/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1090, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHabilidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHabilidad1ActionPerformed

    private void btnHabilidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHabilidad2ActionPerformed

    private void btnHabilidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilidad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHabilidad3ActionPerformed

    private void btnHabilidad1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabilidad1MouseEntered
        getBtnHabilidad1().setBackground(new Color(255, 204, 0));
        getBtnHabilidad1().setForeground(new Color(42, 42, 42));
        getBtnHabilidad1().setBorder(BorderFactory.createLineBorder(new Color(212, 161, 0), 2));
    }//GEN-LAST:event_btnHabilidad1MouseEntered

    private void btnHabilidad2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabilidad2MouseEntered
        getBtnHabilidad2().setBackground(new Color(255, 204, 0));
        getBtnHabilidad2().setForeground(new Color(42, 42, 42));
        getBtnHabilidad2().setBorder(BorderFactory.createLineBorder(new Color(212, 161, 0), 2));
    }//GEN-LAST:event_btnHabilidad2MouseEntered

    private void btnHabilidad3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabilidad3MouseEntered
        getBtnHabilidad3().setBackground(new Color(255, 204, 0));
        getBtnHabilidad3().setForeground(new Color(42, 42, 42));
        getBtnHabilidad3().setBorder(BorderFactory.createLineBorder(new Color(212, 161, 0), 2));
    }//GEN-LAST:event_btnHabilidad3MouseEntered

    private void btnHabilidad4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabilidad4MouseEntered
        getBtnHabilidad4().setBackground(new Color(255, 204, 0));
        getBtnHabilidad4().setForeground(new Color(42, 42, 42));
        getBtnHabilidad4().setBorder(BorderFactory.createLineBorder(new Color(212, 161, 0), 2));
    }//GEN-LAST:event_btnHabilidad4MouseEntered

    private void btnHabilidad1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabilidad1MouseExited
        getBtnHabilidad1().setBackground(new Color(0, 116, 217));
        getBtnHabilidad1().setForeground(new Color(255, 255, 255));
        getBtnHabilidad1().setBorder(BorderFactory.createLineBorder(new Color(0, 86, 163), 2));
    }//GEN-LAST:event_btnHabilidad1MouseExited

    private void btnHabilidad2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabilidad2MouseExited
        getBtnHabilidad2().setBackground(new Color(0, 116, 217));
        getBtnHabilidad2().setForeground(new Color(255, 255, 255));
        getBtnHabilidad2().setBorder(BorderFactory.createLineBorder(new Color(0, 86, 163), 2));
    }//GEN-LAST:event_btnHabilidad2MouseExited

    private void btnHabilidad3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabilidad3MouseExited
        getBtnHabilidad3().setBackground(new Color(0, 116, 217));
        getBtnHabilidad3().setForeground(new Color(255, 255, 255));
        getBtnHabilidad3().setBorder(BorderFactory.createLineBorder(new Color(0, 86, 163), 2));
    }//GEN-LAST:event_btnHabilidad3MouseExited

    private void btnHabilidad4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabilidad4MouseExited
        getBtnHabilidad4().setBackground(new Color(0, 116, 217));
        getBtnHabilidad4().setForeground(new Color(255, 255, 255));
        getBtnHabilidad4().setBorder(BorderFactory.createLineBorder(new Color(0, 86, 163), 2));
    }//GEN-LAST:event_btnHabilidad4MouseExited

    private void btnHabilidad1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabilidad1MousePressed
        getBtnHabilidad1().setBackground(new Color(0, 116, 217));
        getBtnHabilidad1().setForeground(new Color(255, 255, 255));
        getBtnHabilidad1().setBorder(BorderFactory.createLineBorder(new Color(0, 86, 163), 2));
    }//GEN-LAST:event_btnHabilidad1MousePressed

    private void btnHabilidad2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabilidad2MousePressed
        getBtnHabilidad2().setBackground(new Color(0, 116, 217));
        getBtnHabilidad2().setForeground(new Color(255, 255, 255));
        getBtnHabilidad2().setBorder(BorderFactory.createLineBorder(new Color(0, 86, 163), 2));
    }//GEN-LAST:event_btnHabilidad2MousePressed

    private void btnHabilidad3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabilidad3MousePressed
        getBtnHabilidad3().setBackground(new Color(0, 116, 217));
        getBtnHabilidad3().setForeground(new Color(255, 255, 255));
        getBtnHabilidad3().setBorder(BorderFactory.createLineBorder(new Color(0, 86, 163), 2));
    }//GEN-LAST:event_btnHabilidad3MousePressed

    private void btnHabilidad4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabilidad4MousePressed
        getBtnHabilidad4().setBackground(new Color(0, 116, 217));
        getBtnHabilidad4().setForeground(new Color(255, 255, 255));
        getBtnHabilidad4().setBorder(BorderFactory.createLineBorder(new Color(0, 86, 163), 2));
    }//GEN-LAST:event_btnHabilidad4MousePressed

    private void btnInicialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicialMouseEntered
        getBtnInicial().setBackground(new Color(255, 204, 0));
        getBtnInicial().setForeground(new Color(42, 42, 42));
        getBtnInicial().setBorder(BorderFactory.createLineBorder(new Color(212, 161, 0), 2));
    }//GEN-LAST:event_btnInicialMouseEntered

    private void btnInicialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicialMouseExited
        getBtnInicial().setBackground(new Color(0, 116, 217));
        getBtnInicial().setForeground(new Color(255, 255, 255));
        getBtnInicial().setBorder(BorderFactory.createLineBorder(new Color(0, 86, 163), 2));
    }//GEN-LAST:event_btnInicialMouseExited

    private void btnInicialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicialMousePressed
        getBtnInicial().setBackground(new Color(0, 116, 217));
        getBtnInicial().setForeground(new Color(255, 255, 255));
        getBtnInicial().setBorder(BorderFactory.createLineBorder(new Color(0, 86, 163), 2));
    }//GEN-LAST:event_btnInicialMousePressed

    private void btnInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicialActionPerformed
        getTxtAreaInicial().setVisible(false);
        getBtnInicial().setVisible(false);
        getImgInicio().setVisible(false);
        getImgInicio1().setVisible(false);
    }//GEN-LAST:event_btnInicialActionPerformed

    public JButton getBtnHabilidad1() {
        return btnHabilidad1;
    }

    public void setBtnHabilidad1(JButton btnHabilidad1) {
        this.btnHabilidad1 = btnHabilidad1;
    }

    public JTextArea getTxtArea() {
        return txtArea;
    }

    public void setTxtArea(JTextArea txtArea) {
        this.txtArea = txtArea;
    }
    
    public void setBtnHabilidad1ActionListener(ActionListener listener) {
        btnHabilidad1.addActionListener(listener);
    }
    
    public void setBtnHabilidad2ActionListener(ActionListener listener) {
        btnHabilidad2.addActionListener(listener);
    }
    
    public void setBtnHabilidad3ActionListener(ActionListener listener) {
        btnHabilidad3.addActionListener(listener);
    }
    
    public void setBtnHabilidad4ActionListener(ActionListener listener) {
        btnHabilidad4.addActionListener(listener);
    }

    public JLabel getBulbasaurPng() {
        return bulbasaurPng;
    }

    public void setBulbasaurPng(JLabel bulbasaurPng) {
        this.bulbasaurPng = bulbasaurPng;
    }

    public JButton getBtnHabilidad2() {
        return btnHabilidad2;
    }

    public void setBtnHabilidad2(JButton btnHabilidad2) {
        this.btnHabilidad2 = btnHabilidad2;
    }

    public JButton getBtnHabilidad3() {
        return btnHabilidad3;
    }

    public void setBtnHabilidad3(JButton btnHabilidad3) {
        this.btnHabilidad3 = btnHabilidad3;
    }

    public JButton getBtnHabilidad4() {
        return btnHabilidad4;
    }

    public void setBtnHabilidad4(JButton btnHabilidad4) {
        this.btnHabilidad4 = btnHabilidad4;
    }

    public JLabel getTxtVidaOak() {
        return txtVidaOak;
    }

    public void setTxtVidaOak(JLabel txtVidaOak) {
        this.txtVidaOak = txtVidaOak;
    }

    public JLabel getTxtVidaPokemon() {
        return txtVidaPokemon;
    }

    public void setTxtVidaPokemon(JLabel txtVidaPokemon) {
        this.txtVidaPokemon = txtVidaPokemon;
    }

    public JButton getBtnInicial() {
        return btnInicial;
    }

    public void setBtnInicial(JButton btnInicial) {
        this.btnInicial = btnInicial;
    }

    public JTextArea getTxtAreaInicial() {
        return txtAreaInicial;
    }

    public void setTxtAreaInicial(JTextArea txtAreaInicial) {
        this.txtAreaInicial = txtAreaInicial;
    }

    public JLabel getImgInicio() {
        return imgInicio;
    }

    public void setImgInicio(JLabel imgInicio) {
        this.imgInicio = imgInicio;
    }

    public JLabel getImgInicio1() {
        return imgInicio1;
    }

    public void setImgInicio1(JLabel imgInicio1) {
        this.imgInicio1 = imgInicio1;
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameCombate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameCombate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameCombate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameCombate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameCombate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHabilidad1;
    private javax.swing.JButton btnHabilidad2;
    private javax.swing.JButton btnHabilidad3;
    private javax.swing.JButton btnHabilidad4;
    private javax.swing.JButton btnInicial;
    private javax.swing.JLabel bulbasaurPng;
    private javax.swing.JLabel imgInicio;
    private javax.swing.JLabel imgInicio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextArea txtAreaInicial;
    private javax.swing.JLabel txtVidaOak;
    private javax.swing.JLabel txtVidaPokemon;
    // End of variables declaration//GEN-END:variables
}
